jobs:
  - job: "Build_and_Test_StigEval_Module"
    pool:
      name: "Systems"
    steps:
    - powershell: ./build.ps1 -Task Test -Bootstrap -Verbose
      displayName: 'Build and Test'
    - task: PublishTestResults@2
      inputs:
        testRunner: 'NUnit'
        testResultsFiles: '**/output/Artifacts/*.xml'
        testRunTitle: 'Tests'
      displayName: 'Test Results'
    - powershell: ./build.ps1 -Task Release -Verbose
      displayName: 'Package module'

